### ISSUE TITLE
Bad looks

### ISSUE THREAD

**Issue by KiritoChwan** [Narthorn/reStrat#15]
Kiritochwan: can you
Kiritochwan: order the timer display
Kiritochwan: the ones ending sooner on top? :3
Narthorn: I will punch you in the head
Kiritochwan: can you
Narthorn: yes I can
Narthorn: and I will
Kiritochwan: make it look better aswell
Narthorn: and it's long overdue
Kiritochwan: can you add an option
Kiritochwan: transparent bars
Kiritochwan: and ability to change the height
Kiritochwan: of the bars

**Comment by Narthorn** [comment]
Please make 1 ticket for each separate issue.

;)

**Comment by KiritoChwan** [comment]
Narthorn: I will punch you in the head
